export const ProjectData = [
    {
        id: 0,
        imgUrl: '/img/proshopmaster.png',
        name: 'mern',
        comment: 'Online internet Market',
        comment1: `Irure ut voluptate esse et anim non sint. Minim aute esse ipsum laboris esse elit cillum culpa nostrud eiusmod ipsum. Dolor consequat veniam irure consequat elit. Enim aute tempor culpa anim officia adipisicing esse culpa aliquip. Eu Lorem consectetur mollit ad est culpa sint est cillum velit. Occaecat mollit tempor id qui est.`,
        url: 'https://proshopmaster.herokuapp.com/',
        rating: 0,
    },
    {
        id: 1,
        imgUrl: '/img/musicProject.png',
        name: 'node js',
        comment: 'Project for Musics',
        comment1: `This project is about music. In the project you can create, edit and delete. Firstly: you should download “MongoDB”, “NodeJS” and install both of them. Secondly: you should make clone “Git Repository” from the Github. Than you should do “npm install”.`,
        url: 'https://github.com/Mirzamurod/newProjectMusic',
        rating: 0,
    },
    {
        id: 2,
        imgUrl: '/img/reactsearch.png',
        name: 'react',
        comment: 'Add Information and Search',
        comment1: `Irure ut voluptate esse et anim non sint. Minim aute esse ipsum laboris esse elit cillum culpa nostrud eiusmod ipsum. Dolor consequat veniam irure consequat elit. Enim aute tempor culpa anim officia adipisicing esse culpa aliquip. Eu Lorem consectetur mollit ad est culpa sint est cillum velit. Occaecat mollit tempor id qui est.`,
        url: 'https://reactexsearch.netlify.app/',
        rating: 0,
    },
    {
        id: 3,
        imgUrl: '/img/callaneducation.png',
        name: 'react',
        comment: 'Site for Educational Institutions',
        comment1: `Irure ut voluptate esse et anim non sint. Minim aute esse ipsum laboris esse elit cillum culpa nostrud eiusmod ipsum. Dolor consequat veniam irure consequat elit. Enim aute tempor culpa anim officia adipisicing esse culpa aliquip. Eu Lorem consectetur mollit ad est culpa sint est cillum velit. Occaecat mollit tempor id qui est.`,
        url: 'https://callanacademy.netlify.app/',
        rating: 0,
    },
    {
        id: 4,
        imgUrl: '/img/comingsoon1.png',
        name: 'node js',
        comment: 'Online Chat Mainly for Correspondence',
        comment1: `This project is chat. In the project you can create, edit and delete. Firstly: you should download "MongoDB", "NodeJS" and install both of them. Secondly: you should make clone "Git Repository" from the Github. Than you should do "npm install". And You enter the required information in the .env file. Finally you should do "npm start"`,
        url: 'https://github.com/Mirzamurod/chatogram',
        rating: 0,
    },
    {
        id: 5,
        imgUrl: '/img/comingsoon1.png',
        name: 'node js',
        comment: 'Online chat for correspondence',
        comment1: `This project is chat. In the project you can create, edit and delete. Firstly: you should download “MongoDB”, “NodeJS” and install both of them. Secondly: you should make clone “Git Repository” from the Github. Than you should do “npm install”.`,
        url: 'https://github.com/Mirzamurod/WebSocketProjectJonliToplar',
        rating: 0,
    },
]
